driver:
  name: vagrant
  require_chef_omnibus: 12.13.37

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[webserver_test::default]
    attributes:
